name: Weekly Scrape Reviews

on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch: {}

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install undetected-chromedriver
      - name: Run scraper
        env:
          DOMO_WEBHOOK_URL: ${{ secrets.DOMO_WEBHOOK_URL }}
        run: ppython StoaGoogleReviewScraper.py --once
